### ISSUE TITLE
Escape illegal XML characters

### ISSUE THREAD

**Issue by mlange-42** [nikolaydubina/treemap#20]
Some characters that are illegal in XML strings break SVG rendering. These characters should be escaped.

Encountered the issue in my little Go learning project [dirstat](https://github.com/mlange-42/dirstat), which uses `treemap` to visualize disk usage. File and directory names may contain such characters.

Looks like the relevant characters are only those:

* `"`   `&quot;`
* `'`   `&apos;`
* `<`   `&lt;`
* `>`   `&gt;`
* `&`   `&amp;`

**Comment by nikolaydubina** [comment]
Nice! Thanks for reporting. Def will need to fix this. Feel free to make
PR(with unit test or example file and Make) or I will make it!

**Comment by mlange-42** [comment]
Will see if I find the time, so no hurry!
